### ISSUE TITLE
oauth_problem

### ISSUE THREAD

**Issue by antoniosoares** [nickvane/Magento-RestApi#1]
Hi,

I am receiving the message 'oauth_problem=parameter_absent&oauth_parameters_absent=oauth_consumer_key' when creating the client:

var client = new MagentoApi()
            .Initialize("http://www.myshop.com", "Key....", "Secret") // from OAuth Consumers
            .AuthenticateAdmin("admin", "mypassword");  // normal admin login / password

I have configured the REST API configuration the following way:
1) Created a new OAuth Consumer
2) Grant All access to Admin Role
I am using Magento version 1.7.0.2
Did I miss something?

Thanks

António

**Comment by sanghreaajit** [comment]
Hi
I m also facing the same issue.Can you tell me what i m doing wrong here.

 var client = new MagentoApi()
    .SetCustomAdminUrlPart("Custome_admin")
    .Initialize("https://www.magentostore.com/", "xxxxxx", "xxxxxxxxx")
    .AuthenticateAdmin("user", "password");
![magento](https://cloud.githubusercontent.com/assets/12188266/7417111/6b337418-ef81-11e4-8a29-8d6f05fed99d.png)

**Comment by Maxhodges** [comment]
Hi solved it by opening a Shopify store. Shopify is brilliant! So much better than Magento. I wish I had never installed Magento. Wasted so much time dealing with that mess. It takes minutes in Shopify to do things would would take hours or days to do in Magento. The API is much easier to use and better documented.

**Comment by nexrobr** [comment]
Nexcess support here. I realize this is an old thread, but it is still one of the first search hits for this issue; so I'm posting our solution here, in case it is useful to anyone else.

On our systems, the issue is Apache stripping out the Authorization and Content-Type headers. We resolve this by adding the following to the vhost:

SetEnvIf REDIRECT_HTTP_AUTHORIZATION (.+) HTTP_AUTHORIZATION=$1
SetEnvIf REDIRECT_HTTP_CONTENT_TYPE (.+) HTTP_CONTENT_TYPE=$1
