### ISSUE TITLE
authenticate as customer feature

### ISSUE THREAD

**Issue by goopter** [nickvane/Magento-RestApi#16]
as far as I know this is only for authenticate as admin, could you implement the authenticate as customer? I would be very happy to have this feature, so I can develop app to simulate all the features as the front web page has

**Comment by nickvane** [comment]
This is actually available now in the library.
You need to execute the normal oauth procedure and let the user log in into Magento.
After that you will get an accessTokenKey and AccessTokenSecret. You can then use these to get a Magento client (use SetAccessToken(string accessTokenKey, string accessTokenSecret) instead of AuthenticateAdmin).
The goal of this library is for usage where you are not able to ask the user for a login.
And if you're logging in with a user and not an admin, some methods and data will not be available.

**Comment by goopter** [comment]
Thanks Nick, did you just add the feature recently or it's been there since
beginning? As far as I know the login to Magento admin and front end flows
are quite different, and your authentication logic is basically to simulate
the action of clicking authorize on the web page, then retrieve the token
and secret from the string on the web page, does your code allow user
provide user email and password to do auto login?

**Comment by nickvane** [comment]
It would be possible to do the same with minor adjustments. It's just a different page to login.
Authentication with the token and secret have been there from the beginning.
If a user does oauth like it should be done, than this method can be used. 
I might look into it to support user authentication.

**Comment by goopter** [comment]
Did you add the customer login recently?

On Tue, Aug 18, 2015 at 3:31 PM, Nick Van Eeckhout <notifications@github.com
